// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	instance "github.com/LaFabric-LinkTIC/FlowEngine/internal/domain/instance"
	mock "github.com/stretchr/testify/mock"

	shared "github.com/LaFabric-LinkTIC/FlowEngine/internal/domain/shared"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Count provides a mock function with given fields: ctx
func (_m *Repository) Count(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByStatus provides a mock function with given fields: ctx, status
func (_m *Repository) CountByStatus(ctx context.Context, status instance.Status) (int64, error) {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, instance.Status) (int64, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, instance.Status) int64); ok {
		r0 = rf(ctx, status)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, instance.Status) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByWorkflowID provides a mock function with given fields: ctx, workflowID
func (_m *Repository) CountByWorkflowID(ctx context.Context, workflowID shared.ID) (int64, error) {
	ret := _m.Called(ctx, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for CountByWorkflowID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID) (int64, error)); ok {
		return rf(ctx, workflowID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID) int64); ok {
		r0 = rf(ctx, workflowID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.ID) error); ok {
		r1 = rf(ctx, workflowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *Repository) Delete(ctx context.Context, id shared.ID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, id
func (_m *Repository) Exists(ctx context.Context, id shared.ID) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindActive provides a mock function with given fields: ctx
func (_m *Repository) FindActive(ctx context.Context) ([]*instance.Instance, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindActive")
	}

	var r0 []*instance.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*instance.Instance, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*instance.Instance); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*instance.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx
func (_m *Repository) FindAll(ctx context.Context) ([]*instance.Instance, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*instance.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*instance.Instance, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*instance.Instance); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*instance.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *Repository) FindByID(ctx context.Context, id shared.ID) (*instance.Instance, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *instance.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID) (*instance.Instance, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID) *instance.Instance); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*instance.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.ID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByParentID provides a mock function with given fields: ctx, parentID
func (_m *Repository) FindByParentID(ctx context.Context, parentID shared.ID) ([]*instance.Instance, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByParentID")
	}

	var r0 []*instance.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID) ([]*instance.Instance, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID) []*instance.Instance); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*instance.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.ID) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByStatus provides a mock function with given fields: ctx, status
func (_m *Repository) FindByStatus(ctx context.Context, status instance.Status) ([]*instance.Instance, error) {
	ret := _m.Called(ctx, status)

	if len(ret) == 0 {
		panic("no return value specified for FindByStatus")
	}

	var r0 []*instance.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, instance.Status) ([]*instance.Instance, error)); ok {
		return rf(ctx, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, instance.Status) []*instance.Instance); ok {
		r0 = rf(ctx, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*instance.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, instance.Status) error); ok {
		r1 = rf(ctx, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByWorkflowID provides a mock function with given fields: ctx, workflowID
func (_m *Repository) FindByWorkflowID(ctx context.Context, workflowID shared.ID) ([]*instance.Instance, error) {
	ret := _m.Called(ctx, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for FindByWorkflowID")
	}

	var r0 []*instance.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID) ([]*instance.Instance, error)); ok {
		return rf(ctx, workflowID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID) []*instance.Instance); ok {
		r0 = rf(ctx, workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*instance.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.ID) error); ok {
		r1 = rf(ctx, workflowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByWorkflowIDAndStatus provides a mock function with given fields: ctx, workflowID, status
func (_m *Repository) FindByWorkflowIDAndStatus(ctx context.Context, workflowID shared.ID, status instance.Status) ([]*instance.Instance, error) {
	ret := _m.Called(ctx, workflowID, status)

	if len(ret) == 0 {
		panic("no return value specified for FindByWorkflowIDAndStatus")
	}

	var r0 []*instance.Instance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID, instance.Status) ([]*instance.Instance, error)); ok {
		return rf(ctx, workflowID, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.ID, instance.Status) []*instance.Instance); ok {
		r0 = rf(ctx, workflowID, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*instance.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.ID, instance.Status) error); ok {
		r1 = rf(ctx, workflowID, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, query, workflowID
func (_m *Repository) List(ctx context.Context, query shared.ListQuery, workflowID *shared.ID) ([]*instance.Instance, int64, error) {
	ret := _m.Called(ctx, query, workflowID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*instance.Instance
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, shared.ListQuery, *shared.ID) ([]*instance.Instance, int64, error)); ok {
		return rf(ctx, query, workflowID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, shared.ListQuery, *shared.ID) []*instance.Instance); ok {
		r0 = rf(ctx, query, workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*instance.Instance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, shared.ListQuery, *shared.ID) int64); ok {
		r1 = rf(ctx, query, workflowID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, shared.ListQuery, *shared.ID) error); ok {
		r2 = rf(ctx, query, workflowID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Save provides a mock function with given fields: ctx, _a1
func (_m *Repository) Save(ctx context.Context, _a1 *instance.Instance) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *instance.Instance) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
