// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	event "github.com/LaFabric-LinkTIC/FlowEngine/internal/domain/event"
	mock "github.com/stretchr/testify/mock"
)

// Dispatcher is an autogenerated mock type for the Dispatcher type
type Dispatcher struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: ctx, _a1
func (_m *Dispatcher) Dispatch(ctx context.Context, _a1 event.DomainEvent) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Dispatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, event.DomainEvent) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DispatchBatch provides a mock function with given fields: ctx, events
func (_m *Dispatcher) DispatchBatch(ctx context.Context, events []event.DomainEvent) error {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for DispatchBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []event.DomainEvent) error); ok {
		r0 = rf(ctx, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDispatcher creates a new instance of Dispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dispatcher {
	mock := &Dispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
